<?php
/**
 * @file
 * Panels Omega 3 Col 3-3-6 Stacked
 *
 * Copyright (c) 2010-2011 Board of Trustees, Leland Stanford Jr. University
 * This software is open-source licensed under the GNU Public License Version 2 or later
 * The full license is available in the LICENSE.TXT file at the root of this repository
 */

$plugin = array(
    'title' => t('Three column 3-3-6 stacked'),
    'category' => t('Highwire'),
    'icon' => 'omega_3col_3_3_6_stacked.png',
    'theme' => 'faichi_panels_3col_3_3_6_stacked',
    //'admin css' => '../omega_panels_admin_12.css',
    'regions' => array(
      'top' => t('Top'),
      'left' => t('Left side'),
      'middle' => t('Middle column'),
      'right' => t('Right side'),
      'bottom' => t('Bottom'),
    ),
  );
